Introduce DocC page
giginet/Scipio pull request #96
Opened 2023-08-14 13:58 UTC by giginet

closes #60 closes #77

2023-08-15 00:08 UTC, omochi requested changes
ザッと見ました。
気になったところにコメントしました。

2023-08-15 00:08 UTC, omochi commented on Sources/scipio/scipio.docc/installation.md
> +$ swift run -c release scipio --help
他のドキュメントで `scipio` コマンドが使えることを仮定してるので、
パスを通す事を示しておいたほうが良いと思います。

```suggestion
$ swift run -c release scipio --help
# Add reference .build/release/scipio to the PATH variable.
$ vim ~/.bash_profile
```

2023-08-15 03:54 UTC, giginet commented on Sources/scipio/scipio.docc/installation.md
> +$ swift run -c release scipio --help
bash is not a default shell of macOS.

So it's better to just export this.

```
$ export PATH=/path/to/scipio:$PATH
```

2023-08-15 03:54 UTC, giginet commented on Sources/scipio/scipio.docc/create-frameworks.md
> +$ swift create --platforms iOS --platforms watchOS path/to/swift-log
oops

2023-08-15 04:39 UTC, giginet commented on .github/workflows/docc.yml
> +    if: github.event_name == 'push' && github.branch == 'main'
```suggestion
```

2023-08-15 05:01 UTC, giginet commented on Sources/scipio/scipio.docc/create-frameworks.md
> +It's highly recommended to generate Library Evolution to distribute built XCFrameworks.
```suggestion
It's highly recommended to enable Library Evolution to distribute built XCFrameworks.
```

2023-08-15 05:02 UTC, giginet commented on Sources/scipio/scipio.docc/installation.md
> +$ git clone git@github.com:giginet/Scipio.git
```suggestion
$ git clone https://github.com/giginet/Scipio.git
```

2023-08-15 06:09 UTC, giginet commented on Sources/scipio/scipio.docc/installation.md
> +$ swift run -c release scipio --help
```suggestion
$ swift run -c release scipio --help
# Add reference .build/release/scipio to the PATH variable.
$ export PATH=/path/to/scipio:$PATH
```

2023-08-15 06:10 UTC, giginet commented on Sources/scipio/scipio.docc/build-pipeline.md
> +See details for <doc:using-s3-storage>
```suggestion
See details in <doc:using-s3-storage>
```

2023-08-15 06:11 UTC, giginet commented on Sources/scipio/scipio.docc/build-pipeline.md
> +See details for documents of ScipioKit.
```suggestion
See details for documents in ScipioKit. (In Progress)
```

2023-08-15 07:41 UTC, omochi approved these changes

2023-08-16 02:22 UTC, freddi-kit commented on .github/workflows/tests.yml
> +  DEVELOPER_DIR: "/Applications/Xcode_14.3.1.app/Contents/Developer"
これ本当に常に "/Applications" 以下なんです？

2023-08-16 02:22 UTC, freddi-kit commented on Sources/scipio/scipio.docc/build-pipeline.md
> +## Benefits to Implement a Build Script
```suggestion
## Benefits to Implement a Build Script by `ScipioKit`
```

2023-08-16 06:23 UTC, giginet commented on Sources/scipio/scipio.docc/prepare-cache-for-applications.md
> +All XCFrameworks are generated into `MyAppDependencies/XCFramework` by default.
This topic is basic knowledge to develop iOS apps. So we needn't explain this here
Do you know any references?

2023-08-16 06:25 UTC, freddi-kit commented on Sources/scipio/scipio.docc/prepare-cache-for-applications.md
> +All XCFrameworks are generated into `MyAppDependencies/XCFramework` by default.
Example: https://www.simpleswiftguide.com/how-to-add-xcframework-to-xcode-project/

2023-08-16 06:28 UTC, giginet commented on .github/workflows/tests.yml
> +  DEVELOPER_DIR: "/Applications/Xcode_14.3.1.app/Contents/Developer"
This is a spec of GitHub Action Runner. So there is no problem.

https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#xcode

2023-08-16 06:37 UTC, freddi-kit approved these changes

2023-08-16 07:47 UTC, giginet commented on Sources/scipio/scipio.docc/prepare-cache-for-applications.md
> +All XCFrameworks are generated into `MyAppDependencies/XCFramework` by default.
Added https://github.com/giginet/Scipio/pull/96/commits/0dbe03723796be4e06c39100554724fd9f9f939c

2023-08-16 07:50 UTC, freddi-kit approved these changes

2023-08-16 07:52 UTC, giginet commented on Sources/scipio/scipio.docc/prepare-cache-for-applications.md
> +> Note: You can use built in a regular way XCFrameworks to your project. Refer to this document <https://www.simpleswiftguide.com/how-to-add-xcframework-to-xcode-project/>
```suggestion
> Note: You can use built XCFrameworks in a regular way for your project. Refer to this document <https://www.simpleswiftguide.com/how-to-add-xcframework-to-xcode-project/>
```

2023-08-16 08:34 UTC, merged